binop_separator = "Front"

blank_lines_lower_bound = 0

blank_lines_upper_bound = 1

brace_style = "PreferSameLine"

chain_width = 0

combine_control_expr = true

#comment_width = 40

condense_wildcard_suffixes = false

control_brace_style = "AlwaysSameLine"

empty_item_single_line = false

enum_discrim_align_threshold = 20

#fn_call_width = 10

fn_params_layout = "Vertical"

fn_single_line = true

force_explicit_abi = true

force_multiline_blocks = true

format_code_in_doc_comments = true

format_strings = true

struct_lit_single_line = false

struct_lit_width = 1

struct_variant_width = 1

single_line_if_else_max_width = 0

hard_tabs = true

hex_literal_case = "Upper"

#float_literal_trailing_zero = "Never"

show_parse_errors = true

imports_indent = "Block"

imports_layout = "HorizontalVertical"

indent_style = "Block"

inline_attribute_width = 0

match_arm_blocks = true

match_arm_leading_pipes = "Never"

match_block_trailing_comma = true

max_width = 80

merge_derives = false

imports_granularity = "Item"

normalize_comments = true

normalize_doc_attributes = true

overflow_delimited_expr = false

remove_nested_parens = true

reorder_impl_items = true

reorder_imports = false

group_imports = "StdExternalCrate"

reorder_modules = false

space_after_colon = true

space_before_colon = true

spaces_around_ranges = false

tab_spaces = 2

trailing_comma = "Vertical"

trailing_semicolon = true

type_punctuation_density = "Wide"

use_field_init_shorthand = true

use_small_heuristics = "Default"

use_try_shorthand = true

where_single_line = false

wrap_comments = true
